# Generated by Django 6.0 on 2025-12-11 22:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('timer_count', models.SmallIntegerField(default=0)),
                ('status', models.SmallIntegerField(choices=[(0, 'Stopped'), (1, 'Running')], default=0)),
            ],
        ),
    ]
