# Generated by Django 6.0 on 2026-02-05 01:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_timer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
