# Generated by Django 6.0 on 2026-02-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0003_timer_created_at_timer_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
    ]
